{% set name = "pyflowline" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyflowline-{{ version }}.tar.gz
  sha256: 62b3086aeb0d6cd4a17521f9f58ebe11293b65a8adca4a759eb8cdce5b5ae363

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - gdal ==3.2
    - netcdf4
    - numpy
    - python >=3.8
    - shapely

test:
  imports:
    - pyflowline
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/changliao1025/pyflowline
  summary: River network for Earth Science
  license: BSD-2-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - changliao1025
